name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint_and_format:
    name: Lint & Format check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Prettier check
        run: npm run format:check

      - name: ESLint
        run: npm run lint
